### ISSUE TITLE
[BUG] 构造问题

### ISSUE THREAD

**Issue by FySystem** [MiroKaku/Musa.Runtime#10]
![微信截图_20240801024130](https://github.com/user-attachments/assets/a3d3d862-1d26-4a61-a539-b50e82b3a067)
288行打印的值是正确的
305行的值是错误的乱码
测试在ucxxrt中两行都是正确的
怀疑是构造问题,但如果是直接赋值又没问题
例如`info.ImageName = L"abc"`

**Comment by MiroKaku** [comment]
行为没有错，你使用的是 wstring_view，直接引用的 shared_ptr 持有的内存地址，而不是像 wstring 会重新分配内存并copy。当 Process() 函数结束后，shared_ptr 自动释放。地址就无效了。

Musa.Runtime 和 ucxxrt 都没有去改变 STL 实现逻辑。出现不一致的情况可能是因为 ucxxrt 没有实现 debug 版本的堆实现。 Musa.Runtime 是完整实现。

**Comment by MiroKaku** [comment]
![图片](https://github.com/user-attachments/assets/a6ecffde-bb0c-4734-9158-38fc865b6167)
https://zh.cppreference.com/w/cpp/string/basic_string_view
