### ISSUE TITLE
使用NuGet包（>= 0.3.1）添加到VS2019

### ISSUE THREAD

**Issue by awaqq520** [MiroKaku/Musa.Runtime#5]
编译提示:

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1189	#error:  The C++ Standard Library forbids macroizing the keyword "else". Enable warning C4005 to find the forbidden define.	ByPass	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xkeycheck.h	205

**Comment by MiroKaku** [comment]
信息不足

**Comment by MiroKaku** [comment]
看起来是你的代码里面定义了 else 宏导致。
Musa.Runtime 默认没有头文件，也没有相关代码，不会产生这种问题。
