### ISSUE TITLE
[BUG]  Error C1001 fatal : 内部编译器错误。

### ISSUE THREAD

**Issue by FySystem** [MiroKaku/Musa.Runtime#6]
使用静态智能指针会触发内部编译错误
![屏幕截图 2024-07-22 201301](https://github.com/user-attachments/assets/acc66229-44ce-48fe-bb91-26e93f906b75)

**Comment by MiroKaku** [comment]
备注：函数内的静态的不平凡对象都会导致编译器内部错误。
